name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    types: [ "opened" , "reopened", "edited", "synchronize" ]

permissions:
  contents: read

jobs:
  build:

    runs-on: '${{ matrix.operating_system }}'
    timeout-minutes: 10
    strategy:
      matrix:
        operating_system: [ 'ubuntu-latest' ]
        php_versions: [ '8.0', '8.1', '8.2' ]
      fail-fast: false

    steps:
      - uses: actions/checkout@v3

      - name: Validate composer.json and composer.lock
        run: composer validate --strict

      - name: Cache Composer packages
        id: composer-cache
        uses: actions/cache@v3
        with:
          path: vendor
          key: ${{ runner.os }}-php-${{ hashFiles('**/composer.lock') }}
          restore-keys: |
            ${{ runner.os }}-php-
      - name: Install dependencies
        run: composer install --prefer-dist --no-progress

      - name: Run security check
        run: composer audit

      - name: Run code style check
        run: ./vendor/bin/phpcs

      - name: Run static analysis
        run: ./vendor/bin/phpstan